language: java

jdk:
  - openjdk16
script:
  - jdk_switcher use openjdk16
  - # do stuff with OpenJDK 16
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk16
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
  - # do stuff with open OpenJDK 16
sudo: false

env:
  global:
    - CODECOV_TOKEN="dc8bb457-5384-4ffa-9be4-046066f4b3a8"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - radiel13@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

